fix: add package:write permission
Signed-off-by: Praful Khanduri <holiodin@gmail.com>

diff --git a/.github/workflows/publish-images.yaml b/.github/workflows/publish-images.yaml
--- a/.github/workflows/publish-images.yaml
+++ b/.github/workflows/publish-images.yaml
@@ -38,7 +38,10 @@ jobs:
         run: git fetch --prune --unshallow
 
       - name: Describe the current state
-        run: git describe --tags
+        run: |
+          # make sure that tags are available, but don't fail the workflow if none exist.
+          git fetch --tags || true
+          git describe --tags || echo "no-tag-$(git rev-parse --short HEAD)"
 
       - name: Set env vars for the job
         run: |
@@ -53,7 +56,8 @@ jobs:
           grep -v '\#' versions.txt | grep autoinstrumentation-apache-httpd | awk -F= '{print "AUTO_INSTRUMENTATION_APACHE_HTTPD_VERSION="$2}' >> $GITHUB_ENV
           grep -v '\#' versions.txt | grep autoinstrumentation-nginx | awk -F= '{print "AUTO_INSTRUMENTATION_NGINX_VERSION="$2}' >> $GITHUB_ENV
           echo "VERSION_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
-          echo "VERSION=$(git describe --tags | sed 's/^v//')" >> $GITHUB_ENV
+          VERSION="$(git describe --tags 2>/dev/null || echo "no-tag-$(git rev-parse --short HEAD)")"
+          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV
 
       - name: Build the binary for each supported architecture
         run: |
@@ -132,12 +136,13 @@ jobs:
 
   slsa-provenance:
     permissions:
+      actions: read
       contents: read
       id-token: write
       packages: write
     needs: publish
     if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
-    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a #v2.1.0
+    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0 # v2.1.0
     with:
       image: ${{ needs.publish.outputs.image }}
       digest: ${{ needs.publish.outputs.digest }}
@@ -149,7 +154,7 @@ jobs:
     permissions:
       contents: write
       id-token: write
-      packages: read
+      packages: write
     runs-on: ubuntu-latest
     needs:
       - publish
@@ -172,6 +177,13 @@ jobs:
           echo "provenance_file=opentelemetry-operator-${RELEASE_TAG}.intoto.jsonl" >> "$GITHUB_OUTPUT"
           echo "sbom_spdx_file=opentelemetry-operator-${RELEASE_TAG}.sbom.spdx.json" >> "$GITHUB_OUTPUT"
           echo "sbom_cyclonedx_file=opentelemetry-operator-${RELEASE_TAG}.sbom.cyclonedx.json" >> "$GITHUB_OUTPUT"
+      
+      - name: Login to GitHub Package Registry
+        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Download SLSA provenance
         env:
